version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_USER: postgres
      POSTGRES_DB: mano
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - ./.env
  python-api:
    build: D:\Mano\pythonAPI\
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - ./.env
